@extends('layout.edit')
@section('content_form')
    @include('template.input',['tmp_name'=>'name','tmp_label'=>'岗位名称','tmp_value'=>$position->name])
    @if($position->level==4)
        @include('template.input',['tmp_name'=>'code','tmp_label'=>'编号','tmp_value'=>$position->code])
    @endif
    @include('template.select',['tmp_name'=>'sign','tmp_label'=>'启用','tmp_selected'=>$position->sign])
    @include('template.select',['tmp_name'=>'check','tmp_label'=>'检查','tmp_selected'=>$position->check])
@endsection
